version: "3.0"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=production
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - api_server
    networks:
      - highfive
  
  api_server:
    container_name: api_server
    build:
      context: .
      dockerfile: ./backend/api_server/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/api_server:/usr/src/app
    networks:
      - highfive
    restart: always

  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - api_server
      - web
    networks:
      - highfive
    # exit code 실패 오류 시 재시작 
    restart: on-failure

networks: 
  highfive:
    driver: bridge