version: "3.0"

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/algorithm
    environment: 
      - FLASK_APP=app
      - FLASK_ENV=development
    command: gunicorn -w 1 --bind 0.0.0.0:5000 app:app --reload
    restart: always