version: "3.0"

services:
  api_server:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: api_server:prod
    container_name: api_server
    ports:
      - 8000:8000
    volumes:
      - ./:/api_server
    restart: always